version: '3.9'
services:

  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:5-fpm
    container_name: wp-wordpress
    #env_file:
      #- .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - WORDPRESS_LOCAL_HOME:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=wordpress.ccjvfewblenh.us-east-1.rds.amazonaws.com
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress_pietro
      - WORDPRESS_DB_PASSWORD=wordpress123

  database:
    # default port 3306
    image: mysql:8
    container_name: wp-database
    #env_file:
      #- .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=wordpress.ccjvfewblenh.us-east-1.rds.amazonaws.com
      - MYSQL_USER=wordpress_pietro
      - MYSQL_PASSWORD=wordpress123
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - MYSQL_LOCAL_HOME:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    #env_file:
     #- .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80"    # http
      - "8443:443"   # https
    volumes:
      - WORDPRESS_LOCAL_HOME:/var/www/html
      - NGINX_CONF:/etc/nginx/conf.d/default.conf
      - NGINX_SSL_CERTS:/etc/ssl:ro
      - NGINX_LOGS:/var/log/nginx
  volumes:
  wordpress:
    driver: local
  database:
    driver: local

  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 8080
#    image: adminer:4
#    container_name: wp-adminer
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    ports:
#      - "9000:8080"

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
