version: '3'
services:
   wordpress:
     image: wordpress:5.2.2-php7.2-fpm
     container_name: wordpress
     restart: unless-stopped
     ports:
         - '9000:9000'
     environment:
       WORDPRESS_DB_HOST: wordpress-pietro.ccjvfewblenh.us-east-1.rds.amazonaws.com
       WORDPRESS_DB_NAME: wordpress-pietro
       WORDPRESS_DB_USER: wordpress_pietro
       WORDPRESS_DB_PASSWORD: wordpress123
     volumes:
       - ./wordpress:/var/www/html

   nginx:
     image: nginx:latest
     container_name: nginx
     restart: unless-stopped
     ports:
       - "80:80"
       - "443:443"
     volumes:
         - ./nginx:/etc/nginx/conf.d
         - ./logs/nginx:/var/log/nginx
         - ./wordpress:/var/www/html
     links:
       - wordpress

   phpmyadmin:
     image: phpmyadmin/phpmyadmin
     restart: unless-stopped
     ports:
       - 3333:80
     environment:
       PMA_HOST: wordpress-pietro.ccjvfewblenh.us-east-1.rds.amazonaws.com
       MYSQL_ROOT_PASSWORD: wordpress_pietro
